default: &default
  adapter: postgresql
  encoding: unicode
  database: hr_dashboard
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432

development:
  <<: *default
  database: hr_dashboard_development

test:
  <<: *default
  database: hr_dashboard_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *primary_production
    database: hr_dashboard_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: hr_dashboard_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: hr_dashboard_production_cable
    migrations_paths: db/cable_migrate
